language: 
 — ruby
rvm:
 — 2.7
cache:
 — bundler
script:
 — bundle install && bin/rails db:create && bin/rails db:migrate
services:
 — postgresql

deploy:
provider: heroku
api_key:
secure: x5oAAZBbr3uI5frDfib+PK4Ry2OzDtXAtZxdHrfkatwXhOd9M7anHrkKg17tY6WE3njwooqnOx1p3j3Gl3exxXfMJh6mClhODqq485AXV08qSDdlcpRsPsnfwo6ilmu+Ek14T2sS0bsQmgxe7dbqQ+GnSZ2RYgsBeAX0SzOhjf9FuriRqymn6RPhzw+jMUZlQ/L7zsRWVtKXxTpyaS3ENQ8uyICkAlsD8Vj9OKloiDEBOhkgjp0+K6N1YSQdi5iSejTbLzduJN04ajTWVhCWTpdHvMNnDaExgPJvMNgPqTPZ7EIo5nIPViEW6+oL2sqn3jOxJAqGA2djSvAqCMHu8NjVUEFzOUae6LNCcPDgvz8K0ka9UQ0qPzem0wKsUeVVNrObGvfALQoTGbvxPrfsjjEtSmfu8mRXU7nC3BxCHUTzAR5O3w/bXY/9phiuoz/HDLetI0lYz+xKhRMZXRGO4X2HNz9xf/WOSNEZSE13UJcb5Syowo8LS7fuPHY2wsReNS050YOoaT7WTldqVoEFERa/9BvQseZM84hRwlbBisIIvg31F7BNzih+xXyliZt9FQ9gFRAIcIVUKafrL1dAHUcPVNG+umxHgBpLb22D2GSX2QhUZNEoq6fPqioAuSWa4oYYSKyax/BnhtPJ8e90dYlnwluMVacxGyWJ60K+Soc=
app: acebook-runtime-terrors-test
on:
repo: ells101/runtime-terrors-heroku-test
